server:
  port: 9097

tg:
  bot:
    name: kookacreq_bot
    token: 6046387088:AAH1seIqRdOHonwiOkXhWZsizGBkus663wQ

backend:
  url: http://localhost:8080/api

storage:
  user-state: userStageStorage
  user-name: userNameStorage
  access-token: accessTokenStorage
  refresh-token: refreshTokenStorage


spring:
  data:
    redis:
      host: localhost
      port: 6379
